apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-deploy
  template:
    metadata:
      labels:
        app: code-deploy
    spec:
      containers:
        - name: code-deploy
          image: farid25/code-generate:v10
          ports:
            - containerPort: 5000 # Adjust port if your Node.js app uses a different one
          envFrom:
            - configMapRef:
                name: api-rate-limit-code
          env:
            - name: OPENAI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: openai-api-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-uri

---
apiVersion: v1
kind: Service
metadata:
  name: code-deploy-service
spec:
  selector:
    app: code-deploy
  ports:
    - port: 5050
      targetPort: 5000
