apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-deploy
  template:
    metadata:
      labels:
        app: music-deploy
    spec:
      containers:
        - name: music-deploy
          image: farid25/music-generate:latest
          ports:
            - containerPort: 7000 # Adjust port if your FastAPI app uses a different one
          envFrom:
            - configMapRef:
                name: api-rate-limit-code
            - configMapRef:
                name: mongodb-name
          env:
            - name: REPLICATE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: replicate-secret
                  key: replicate-api-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-uri
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-name
                  key: cloudinary-cloud-name
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloud-key
                  key: cloudinary-api-key
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: cloudinary-api-secret

---
apiVersion: v1
kind: Service
metadata:
  name: music-deploy-service
spec:
  selector:
    app: music-deploy
  ports:
    - port: 5050
      targetPort: 7000
