apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  openai-api-key: # Base64 encoded token

---
apiVersion: v1
kind: Secret
metadata:
  name: replicate-secret
type: Opaque
data:
  replicate-api-key: # Base64 encoded token

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-uri: # Base64 encoded token
